### ISSUE TITLE
Tool is not working as in paper

### ISSUE THREAD

**Issue by botwithfeelings** [SoftwareEngineeringToolDemos/FSE-2012-SelfMotion#18]
Trying to run SelfMotion from Android Studio:
- Clicking Run goes to the run configuration dialog, clicking the run button doesn't do anything.
- From the AVD manager, if run from the Nexus 5 API emulator, this error message pops up:

"Cannot launch AVD in emulator.
Output:
emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure Intel HAXM is properly installed and usable.
CPU acceleration status: HAX kernel module is not installed."

**Comment by jentsan** [comment]
fixes #18
