### ISSUE TITLE
Project doesn't have any binaries

### ISSUE THREAD

**Issue by botwithfeelings** [SoftwareEngineeringToolDemos/FSE-2012-SelfMotion#3]
Project should have one or more binaries.

**Comment by botwithfeelings** [comment]
I am not sure about this one, SelfMotion doesn't seem to have the notion of binary - since this is more of a programming platform. I will leave this up to your choice, can close using the 'wontfix' label.

**Comment by botwithfeelings** [comment]
@jentsan I would like to close this one, if you think SelfMotion doesn't have any binaries.

**Comment by jentsan** [comment]
Yes, we can close that one because SelfMotion doesn't have binaries.
